### PR TITLE
TCN model

### PR DESCRIPTION
**Pull request by ehrhorn**
Inspired by tsai we've added a temporal convolutional network (TCN).

However, we cannot get the input shapes to match; a TCN expects 3 dim inputs. Adding a fake dimension naturally leads to bad predictions and yields NaNs in short order during training.

As stated during the course, I have been at a conference all week this week - if we can get an extension, I'm sure we can fix this issue!

### CODE REVIEW

**Comment by seshutir** [comment]
@ehrhorn Thank you for the PR. Please take your time (till June 10th?) to resolve the issue.

**Comment by ehrhorn** [comment]
@seshutir Thanks, we'll get it done!

**Comment by FlapKap** [comment]
@seshutir should be good now. Give it  a whirl :)

**Review by dhavalsalwala — APPROVED** [review]
Looks Good To Me.

**Pull request merged**
